# Generated by Django 3.1.7 on 2021-03-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.TextField()),
                ('para_1', models.TextField()),
                ('para_2', models.TextField(blank=True, null=True)),
                ('para_3', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField()),
                ('link', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
