# Generated by Django 3.1.7 on 2021-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='t_and_c',
            field=models.TextField(blank=True, null=True),
        ),
    ]
