# Generated by Django 3.1.7 on 2021-03-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210326_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_1',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_3',
        ),
    ]
