# Generated by Django 3.1.7 on 2021-03-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
